// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bswnatnpapxrkgtdrzhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzd25hdG5wYXB4cmtndGRyemhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0ODcxODEsImV4cCI6MjA1MjA2MzE4MX0.qXs34913NB1DdldPU-_89DpwHTT7YK8EyNZW1S3LV5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);